# Site settings
title: Paul Bulai
email: paul@bulai.me
url: https://paul.bulai.me
#description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#333333'
  links: '#F79A7E'

# Footer settings
footer: Paul Bulai

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/pcbulai
  - title: facebook
    url: https://facebook.com/pcbulai
  - title: github
    url: https://github.com/pcbulai

# Build settings
markdown: kramdown
permalink: pretty
